# Generated by Django 4.0.3 on 2022-10-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_rename_technician_id_service_appointment_technician_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_appointment',
            old_name='technician_name',
            new_name='technician',
        ),
    ]
