# Generated by Django 4.0.3 on 2022-10-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_rename_technician_name_service_appointment_technician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_appointment',
            old_name='vin',
            new_name='add_vin',
        ),
    ]
