# Generated by Django 4.0.3 on 2022-10-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_rename_vin_service_appointment_add_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_appointment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
