# Generated by Django 4.0.3 on 2022-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_service_appointment_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_appointment',
            name='add_vin',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
