# Generated by Django 4.0.3 on 2022-10-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_alter_service_appointment_add_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_appointment',
            name='add_vin',
            field=models.CharField(max_length=200),
        ),
    ]
